### ISSUE TITLE
deleting last buffer opens first

### ISSUE THREAD

**Issue by uloco** [ojroques/nvim-bufdel#2]
When I have multiple buffers open and delete the last opened one (in bufferline it is the one on the far right) it should select the previous buffer but it instead selects the first one.

I tried to fix this with something like this here but it does not take vim tabs into count so it does only work if there is only one vim tab open.
Do you have any clue how to fix this on mine or maybe on your side?

My approach so far:

```lua
local function close()
  local buffers = require("bufferline.utils").get_valid_buffers()
  local buf_count = require("bufferline.utils").get_buf_count()
  local buf_current = vim.fn.bufnr('#')

  local buf_last = buffers[buf_count - 1]

  if (buf_current == buf_last) then
    bufdel.delete_buffer()
    vim.cmd('bprevious')
  else
    bufdel.delete_buffer()
  end
end

```

**Comment by ojroques** [comment]
I have implemented this feature in the latest commit. It's now the default behavior.

**Comment by uloco** [comment]
Thank you so much will give it a try :)))
