### ISSUE TITLE
Close all buffers?

### ISSUE THREAD

**Issue by traverseda** [ojroques/nvim-bufdel#5]
I'm trying to get my vimrc to work as a terminal multiplexer like tmux. Basically I want to map `qa` to `Bufdel all` so that terminals will get closed properly but it will still complain about files with pending edits.

**Comment by ojroques** [comment]
I added a new command `:BufDelAll`. Use `:BufDelAll!` to ignore changes.

**Comment by traverseda** [comment]
Awesome, I appreciate it!
