### ISSUE TITLE
Feature request: Delete from current window only

### ISSUE THREAD

**Issue by danielfalk** [ojroques/nvim-bufdel#6]
First of all, great plugin.  Thanks for putting it out there!

I like how this brings you closer to what you'd expect in most graphical editors, but one thing that I notice is still more intuitive in graphical editors is that if the same file is open in multiple splits, and you close that file in one split, it is still open in the other.  In vim, if you `:bdelete`, it disappears out of both.

Would it be possible to make an option that would make it so that if I do a BufDel, it would remove it from the current window only?  I'm sure it's probably hard to do, and it's counter to vim's behavior, so it's just an idea.

Thanks again and keep up the good work!

**Comment by ojroques** [comment]
Hello!

Glad you like the plugin.

In Vim, a buffer is a file loaded into memory. A window is a container to display a particular buffer. So if you delete a buffer, you effectively remove that file from memory and no window can display that buffer anymore.

If you have 2+ windows with the same buffer displayed in them and want to display something else in one of the window, just switch to another buffer in that window `:bn`.

**Comment by towry** [comment]
1. check if the buffer is loaded in multiple window.
2. If true, hide in current window instead of delete.
3. Otherwise, delete.
