### ISSUE TITLE
Feature request: bufferline.nvim integration

### ISSUE THREAD

**Issue by nagua** [ojroques/nvim-bufdel#7]
Hello everyone,

I'm using https://github.com/akinsho/bufferline.nvim to show all currently open buffers.
It can also be used to manually rearrange the buffers in the bufferline. If I rearrange a
buffers and close a buffer (with `nvim-bufdel` cycle behavior), the next chosen buffer is
not necessarily the next one in the bufferline.

I forked your code and implemented a new `next` mode named `custom_fn` that will
use a custom function to choose the next buffer. I could also directly integrate `bufferline.nvim`
into the code.

Are you willing to accept a PR to incorporate either of those features or both? Do you see
a better way to handle choosing the next buffer then the methods I mentioned?

Have a great day!

**Comment by ojroques** [comment]
Hello ! Yes the first feature `custom_fn` would be great to have :). No need to have both.

**Comment by nagua** [comment]
Ok, I will create a pull request.
